CREATE TABLE IF NOT EXISTS users_events
(
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    confirmation BOOLEAN NOT NULL DEFAULT FALSE,
    owner BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (user_id, event_id)
);